### ISSUE TITLE
Unable start sonar after update sonar from 8.9.2 to 9.2.0 version sonar-findbugs

### ISSUE THREAD

**Issue by rocenpe** [spotbugs/sonar-findbugs#411] opened 2021-11-25 16:54 UTC
Unable start sonar after update sonar from 8.9.2 to 9.2.0 version and findbugs to 4.0.4 version.
Startup finished this error:
2021.11.25 17:48:01 INFO  web[][o.s.s.q.RegisterQualityProfiles] Update profile jsp/FindBugs Security JSP
2021.11.25 17:48:01 ERROR web[][o.s.s.p.Platform] Background initialization failed. Stopping SonarQube
org.sonar.server.exceptions.BadRequestException: Rule was removed: findsecbugs:XSS_JSP_PRINT
        at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:57)
        at org.sonar.server.exceptions.BadRequestException.create(BadRequestException.java:61)
        at org.sonar.server.exceptions.BadRequestException.checkRequest(BadRequestException.java:44)
        at org.sonar.server.qualityprofile.RuleActivator.doActivate(RuleActivator.java:82)
        at org.sonar.server.qualityprofile.RuleActivator.activate(RuleActivator.java:77)
        at org.sonar.server.qualityprofile.BuiltInQProfileUpdateImpl.update(BuiltInQProfileUpdateImpl.java:73)
        at org.sonar.server.qualityprofile.RegisterQualityProfiles.update(RegisterQualityProfiles.java:132)
        at org.sonar.server.qualityprofile.RegisterQualityProfiles.lambda$start$1(RegisterQualityProfiles.java:93)
        at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:405)
        at org.sonar.server.qualityprofile.RegisterQualityProfiles.start(RegisterQualityProfiles.java:88)
        at org.sonar.core.platform.StartableCloseableSafeLifecyleStrategy.start(StartableCloseableSafeLifecyleStrategy.java:40)
        at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.start(AbstractInjectionFactory.java:84)
        at org.picocontainer.behaviors.AbstractBehavior.start(AbstractBehavior.java:169)
        at org.picocontainer.behaviors.Stored$RealComponentLifecycle.start(Stored.java:132)
        at org.picocontainer.behaviors.Stored.start(Stored.java:110)
        at org.picocontainer.DefaultPicoContainer.potentiallyStartAdapter(DefaultPicoContainer.java:1016)
        at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1009)
        at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
        at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
        at org.sonar.server.platform.platformlevel.PlatformLevel.start(PlatformLevel.java:90)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.access$001(PlatformLevelStartup.java:51)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup$1.doPrivileged(PlatformLevelStartup.java:119)
        at org.sonar.server.user.DoPrivileged.execute(DoPrivileged.java:45)
        at org.sonar.server.platform.platformlevel.PlatformLevelStartup.start(PlatformLevelStartup.java:116)
        at org.sonar.server.platform.PlatformImpl.executeStartupTasks(PlatformImpl.java:198)
        at org.sonar.server.platform.PlatformImpl$1.lambda$doRun$1(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.runIfNotAborted(PlatformImpl.java:370)
        at org.sonar.server.platform.PlatformImpl$1.doRun(PlatformImpl.java:122)
        at org.sonar.server.platform.PlatformImpl$AutoStarterRunnable.run(PlatformImpl.java:354)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021.11.25 17:48:01 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
2021.11.25 17:48:02 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
2021.11.25 17:48:02 INFO  web[][o.s.s.e.CoreExtensionStopper] Stopping Governance
2021.11.25 17:48:02 INFO  web[][o.s.s.e.CoreExtensionStopper] Stopping Governance (done) | time=0ms

## Environment
Sonar 8.9.2 to 9.2.0
Findbugs 4.0.4

Thank you for your help.
Blessings,
Petr R.

**Comment by gtoison** [comment] 2021-11-25 17:33
Hello, we are aware of this issue and a new release fixing it should be out very soon.
I will close this as it is a duplicate of https://github.com/spotbugs/sonar-findbugs/issues/387

In case you cannot wait, other users affected have confirmed that the patch in this forked repo was working for them: https://github.com/gtoison/sonar-findbugs/releases/tag/4.0.4.3

**Comment by rocenpe** [comment] 2021-11-25 19:47
Hello Guillaume,
thank you for quick response. I tried install version 4.0.4.3 and sonar start well.
Thank you.
Blessings,
Petr

**Comment by gtoison** [comment] 2021-12-02 17:03
We have released version 4.0.5 with a fix for this bug: https://github.com/spotbugs/sonar-findbugs/releases/tag/4.0.5
It was submitted to the marketplace but not accepted yet (there seem to be a backlog for accepting new releases of plugins).

**Closed by gtoison** 2021-12-02 17:03 UTC
