### ISSUE TITLE
Don't understand "could not be matched to its original source file" warnings

### ISSUE THREAD

**Issue by davidmichaelkarr** [spotbugs/sonar-findbugs#161] opened 2018-02-02 18:44 UTC
We use the Sonar-Findbugs plugin version 3.4.4.

When our scan runs, we see a bunch of lines like the following:

`17:07:59 WARN: The class '...' could not be matched to its original source file. It might be a dynamically generated class.`

For the scan I'm looking at, there were 19 occurrences of this. I've seen other builds where the number was much larger.  In all cases, the class mentioned in the warning is NOT dynamically generated, and is a source file scanned by SonarQube.  I can navigate to the corresponding SonarQube project, and then to each file, and verify it has been scanned and has information on it.

What other information can I provide to try to diagnose this issue?

**Comment by h3xstream** [comment] 2018-02-02 19:10
SpotBugs scan bytecode (classes in jars or folder). In some cases, we are not able to map the class name (`com.company.lib.ClassName`) to it source location (`/src/main/java/com/company/lib/ClassName.java`).

SpotBugs integration for Sonar has many ways to find the original source file even for JSP or special template files. It some case it will fail with custom source folder (this should be fixed.) and special classes or maybe inner our outer classes (again it should be supported).

# Information needed

To resolve this problem, you need to describe what is specific regarding those classes. Look at the class names and the source files associates.

Make sure the source code is compiled in debug mode. This will include source lines mapping and source file mapping inside the compiled classes.
You can use `javap -v MyClass.class` to troubleshoot the state of your compiled artifacts.

**Comment by davidmichaelkarr** [comment] 2018-02-02 19:59
Well, all of the easy checks won't provide an answer. We don't use custom source locations, and all the occurrences I've seen are not inner classes.  Everything is compiled the same way, and we have a few thousand source files. They are compiled with debug.

**Comment by h3xstream** [comment] 2018-02-14 22:27
@davidmichaelkarr If you can share privately or publically the path to one file missing, the class file and/or the export of the files tree, I would be able to troubleshoot this behaviour.

**Closed** 2018-03-14 06:33 UTC
Labels: bug, question, unable-to-reproduce

**Comment by chforster** [comment] 2018-09-05 08:14
I know the Issue is closed but I'm curious: If the File you're talking about is a Unit-Test it can be possible that this error occurs because of the project structure.

We had the same error with the following Project Structure:

    myProject
        |- src
        |- testsrc
        |- classes

The Unit-Test located under "testsrc" was compiled to "classes" and SonarQube resp. the FindBugs Plugin did not find the corresponding Java File within testsrc (because it did not search there).
