### ISSUE TITLE
NOSONAR not ignored

### ISSUE THREAD

**Issue by isaguimiot** [spotbugs/sonar-findbugs#1034] opened 2024-08-22 21:11 UTC
## Issue Description

Some issues **raised by findbugs** have a //NOSONAR tag in the source code, but now they appear in the issues, instead of being ignored.
(see screenshot attached)
![nosonar](https://github.com/user-attachments/assets/e988baf7-7401-405b-a63c-1eeec7d1e06a)

## Environment

We updated Sonarqube to 10.6 and use findbugs 4.2.7 (had to rollback after a bug was introduced in 4.2.8 : "missing bug code for keySECXXEVAL")

There's a topic on sonarqube community about this bug : https://community.sonarsource.com/t/nosonar-does-not-work/97763/4
They say it's a findbugs problem.

Could you investigate ?

**Comment by gtoison** [comment] 2024-08-26 05:54
As far as I know this was never a feature of the findbugs plugin, because it analyses the compiled .class files where there's no `NOSONAR` comment.
I suppose that SonarQube was silencing the issues raised by plugin when there was a `NOSONAR` comment on the line

**Comment by gtoison** [comment] 2024-09-03 15:16
Hello @isaguimiot
I got an answer from Colin at Sonarsource ([here](https://community.sonarsource.com/t/nosonar-does-not-work/97763)) and this is indeed supposed to work, even if the plugin does not check for `NOSONAR`
Since the problem is not reproduced in his testing, Colin is asking if you could provide a sample project reproducing the problem

**Comment by gtoison** [comment] 2024-11-08 12:09
I'll close this since there was no feedback; the plugin (or SpotBugs) do not process the NOSONAR comment. Possibly SonarQube itself processes it to suppress issues?

**Closed by gtoison** 2024-11-08 12:09 UTC

**Comment by divinity76** [comment] 2025-12-18 03:57
This commit generated several sonar  errors despite NOSONAR: https://github.com/mehah/otclient/pull/1491/commits/b8c784c0899f0e2e56f9aab58ff6200e2f261344

like wtf: https://sonarcloud.io/project/security_hotspots?id=mehah_otclient&pullRequest=1491&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true

**Comment by gtoison** [comment] 2025-12-19 05:15
This project here aims to detect bugs in Java code and other JVM languages. The NOSONAR comment is handled by the Sonarqube server, not by this plugin. 
If you think you have an issue you need to report it to the sonarqube community forum
