### ISSUE TITLE
fb-contrib:USFW_UNSYNCHRONIZED_SINGLETON_FIELD_WRITES java rule caught issue in Kotlin Code

### ISSUE THREAD

**Issue by yokum3** [spotbugs/sonar-findbugs#608] opened 2022-07-26 08:32 UTC
##fb-contrib:USFW_UNSYNCHRONIZED_SINGLETON_FIELD_WRITES

## Environment

| Component          | Kotlin|
| ------------------ | ------- |
| SonarQube          | 9.4   |
| Sonar-FindBugs     | fb-contrib:USFW_UNSYNCHRONIZED_SINGLETON_FIELD_WRITES   |
| Maven              | ?????   |
| Gradle             | ?????   |
| Java               | ?????   |

## Code (If needed)

```java
public class BugSample1 {
  public static void hello(String message) {
       
    //Something
    Runnable r = () -> System.out.println(message);
   
    r.run();
![FB_Issue](https://user-images.githubusercontent.com/62380441/180961093-d6947994-7bd2-490a-a104-5ed216bbe8d3.jpg)

  }
}
```

**Comment by yokum3** [comment] 2022-07-26 08:32
![FB_Issue](https://user-images.githubusercontent.com/62380441/180961444-449f076c-f09a-493f-b9cb-ab27e370d64f.jpg)

**Comment by yokum3** [comment] 2022-07-26 08:34
![FB_Issue](https://user-images.githubusercontent.com/62380441/180961764-30ab545c-eff8-4901-9bc6-56017fa2b7d9.jpg)

**Comment by gtoison** [comment] 2022-07-26 11:32
My understanding is that Kotlin auto-generates getters and setters, so even if they are not written, the methods will be present in the bytecode analyzed by SpotBugs. Since the setter is not synchronized the detector reports an issue.

I don't know Kotlin or Spring but from what I understand you should make these setters synchronized: https://stackoverflow.com/questions/45445991/synchronize-property-getters-setters

**Comment by yokum3** [comment] 2022-07-27 07:14
Thanks for your response. But I can also see other rules from java  caught by findbugs plugin in Kotlin code. Below is one more example 
![image](https://user-images.githubusercontent.com/62380441/181185014-2bc8d969-94ed-4354-8e1d-1cf8b905493d.png)

**Comment by gtoison** [comment] 2022-07-27 10:13
[Version 4.2.0](https://github.com/spotbugs/sonar-findbugs/releases/tag/4.2.0) introduced support to report issues in Kotlin code. Unless you think that these are false positives it's a feature, not a bug ;)

**Comment by gtoison** [comment] 2022-08-19 07:10
I will close this as there does not seem to be further questions, please don't hesitate to create a new issue

**Closed by gtoison** 2022-08-19 07:10 UTC
