### ISSUE TITLE
Sonar-findbugs artifacts part of target folder

### ISSUE THREAD

**Issue by Naseem-Banu-prog** [spotbugs/sonar-findbugs#285] opened 2019-09-09 17:08 UTC
Hello,

We are using the Findbugs plugin v3.11.0 hosted in github. When we build the code using the Jenkins, the fb-contrib jar(which is a dependency of Sonar Findbugs plugin as per https://github.com/spotbugs/sonar-findbugs/blob/master/pom.xml ) is seen as part of maven target folder.

Our understanding is that sonar scan is run after the final artifact is generated. How does this fb-contrib jar/findsecbugs-plugin.jar is making it to target folder? we got a security flag for it. Please advise.

**Comment by gtoison** [comment] 2022-01-08 15:12
Sorry for the belated answer, I recently started maintaining the project.
I believe that this is due to https://github.com/spotbugs/sonar-findbugs/issues/278 and should be solved in the newer versions of the plugin

**Comment by gtoison** [comment] 2022-02-18 08:54
This is actually the same issue as https://github.com/spotbugs/sonar-findbugs/issues/128
Unfortunately I've not been able to locate the cause so far
I'll close this issue now and you can follow #128

**Closed by gtoison** 2022-02-18 08:54 UTC
