### ISSUE TITLE
Sonar-Findbugs 3.9.3 incompatible with SonarJava 5.12

### ISSUE THREAD

**Issue by donnchadh** [spotbugs/sonar-findbugs#263] opened 2019-04-13 07:54 UTC
## Issue Description

Having upgraded to SonarJava 5.12, I receive the following error:

> An API incompatibility was encountered while executing org.sonarsource.scanner.maven:sonar-maven-plugin:3.6.0.1398:sonar: java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findSourceFileKeyByClassName(Ljava/lang/String;)Ljava/lang/String;

> build	13-Apr-2019 01:06:01	Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findSourceFileKeyByClassName(Ljava/lang/String;)Ljava/lang/String;
> build	13-Apr-2019 01:06:01	    at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.findSourceFileKeyByClassName (ByteCodeResourceLocator.java:59)
> build	13-Apr-2019 01:06:01	    at org.sonar.plugins.findbugs.FindbugsSensor.findOriginalClassForBug (FindbugsSensor.java:238)
> build	13-Apr-2019 01:06:01	    at org.sonar.plugins.findbugs.FindbugsSensor.execute (FindbugsSensor.java:153)
> build	13-Apr-2019 01:06:01	    at org.sonar.scanner.sensor.SensorWrapper.analyse (SensorWrapper.java:53)
> 

## Environment

| Component          | Version |
| ------------------ | ------- |
| SonarQube          | 6.7.4.38452   |
| Sonar-FindBugs     | 3.9.3   |
| SonarJava     | 5.12   |
| Maven              | 3.5.3  |
| Gradle             | N/A   |
| Java               | 8   |

It appears that Sonar-Findbugs depends on a method in SonarJava that has been deprecated since SonarJava 4.1 and has now been removed.
See this [commit](https://github.com/SonarSource/sonar-java/commit/2484c4dbac763ee4587ac3d3cac6c54575d76b17#diff-54e59e94e3cd473f69b91d81d8f45a4e)

**Comment by phermsdorf** [comment] 2019-04-15 07:30
I reported tthis issue [here](https://community.sonarsource.com/t/api-incompatibility-after-upgrading-from-sonarqube-7-5-to-7-7/8765/3)
They pointed out that a deprecated API was removed with the last release

The problematic code in sonar findbugs is [here](https://github.com/spotbugs/sonar-findbugs/blob/f484f7bcbe8ce89e1a2bfbd455a57467f69e45e7/src/main/java/org/sonar/plugins/findbugs/resource/ByteCodeResourceLocator.java#L59)

**Comment by rocenpe** [comment] 2019-04-15 11:30
We have same problem with FindBugs version 3.10.0 and Sonar java plugin 5.12.

**Comment by charlesfendt** [comment] 2019-04-16 07:52
I get the same bug on a SQ 7.6 with the java plugin 5.12...
Caused by: java.lang.NoSuchMethodError: org.sonar.plugins.java.api.JavaResourceLocator.findSourceFileKeyByClassName(Ljava/lang/String;)Ljava/lang/String;
    at org.sonar.plugins.findbugs.resource.ByteCodeResourceLocator.findSourceFileKeyByClassName (ByteCodeResourceLocator.java:59)
    at org.sonar.plugins.findbugs.FindbugsSensor.findOriginalClassForBug (FindbugsSensor.java:233)
    at org.sonar.plugins.findbugs.FindbugsSensor.execute (FindbugsSensor.java:148)

**Comment by KengoTODA** [comment] 2019-04-16 09:41
note: sonar-java 5.12 supports SonarQube 7.4-alpha2 and later. 
https://github.com/SonarSource/sonar-java/blob/5.12.0.17701/pom.xml#L86

The sonar-findbugs 3.9.3 supports SonarQube 7.4 so it's probably possible to support sonar-java 5.12 in theory.

**Comment by charlesfendt** [comment] 2019-04-25 13:58
I don't know why you are using a File object in findOriginalClassForBug()...
If you can change this to URI, you can replace new File(findSourceFileKeyByClassName(className)) with findResourceByClassName(className).uri()
If you have a look to the documentation this also can be a remote data :
```
  /**
   * Identifier of the file. The only guarantee is that it is unique in the project.
   * You should not assume it is a file:// URI.
   * @since 6.6
   */
URI uri();

```

**Comment by alexsuter** [comment] 2019-04-29 06:59
Any workarounds for this issue? Or should we downgrade to SonarJava?

**Comment by KengoTODA** [comment] 2019-04-29 09:53
currently we have two workarounds:

a. downgrade sonar-java to the previous version
b. build `issue-263` branch that will be released as 3.11 in future

**Comment by muhlba91** [comment] 2019-04-29 10:41
@KengoTODA is there an aproximate ETA for 3.11?

**Comment by pekarp** [comment] 2019-04-29 11:22
Hi @KengoTODA,
we trieded with previous version sonar-java 5.11.0.17289 and Sonar-FindBugs 3.9.3 on SonarQube 6.7.7. Scanner run succeeded with errors but SonarQube cuold not process report (error).
Which version are you refering as previous version for sonar-java 5.12 (5.12.1.17771)?

**Comment by pekarp** [comment] 2019-04-29 12:07
We testaed also with sonar-java-plugin-5.6.1.15064.jar . We get same error with that what we got with sonar-java 5.11.0.17289.
Error on scanner:ERROR: Cannot analyze file xxx//desktop_header.jsp java.lang.UnsupportedOperationException: Trying to save highlighting twice for the same file is not supported: xxx/desktop_header.jsp  

Error on SonarQube: java.lang.IllegalArgumentException: Multiple entries with same key: jsp=JSP and jsp=JSP

**Comment by ahubold** [comment] 2019-04-29 12:22
@pekarp we're using SonarJava 5.11 (build 17289) with Sonar-Findbugs 3.9.3 on SonarQube 6.7.5 without any problems.

But it would still be great to have a Sonar-Findbugs 3.9.x release for SonarQube 6.7.x that works with SonarJava 5.12.x.

**Comment by pekarp** [comment] 2019-04-29 12:47
@ahubold so we should downgrade SonarQube 6.7.7 to 6.7.5

**Comment by ahubold** [comment] 2019-04-29 13:00
@pekarp You may try, but I just haven't tested with 6.7.7. Your error may still have a different cause. Maybe it also depends on analyzed sources. I don't know.

**Closed** 2019-04-30 03:35 UTC
Labels: help wanted

**Comment by pekarp** [comment] 2019-04-30 08:49
Hi @KengoTODA,
what is estimated time than we get this new release 3.11.0?
Is it supported only for SonarQube 7.6~ (https://github.com/spotbugs/sonar-findbug / 3.11-SNAPSHOTs)?
Will there be a fix for SonarQube 6.7.x (6.7.7) LTS version?

We were able to run scan without Findbugs 3.9.3 successfully (SonarQube 6.7.7/sonar-java 5.6)

**Comment by jloisel** [comment] 2019-04-30 09:32
+1 No Java analysis possible on Sonarqube 7.7 due to this bug.

**Comment by valahakula** [comment] 2019-04-30 09:49
We were able to run scan without Findbugs 3.9.3 successfully (SonarQube 6.7.7/sonar-java 5.12.1)
but scanner gave following error both 5.6 and 5.12.1:

ERROR: Error when running: 'node -v'. Is Node.js available during analysis?
org.sonarsource.nodejs.NodeCommandException: Error when running: 'node -v'. Is Node.js available during analysis?

**Comment by cstsw** [comment] 2019-04-30 11:44
+1 Same problem for me (with Sonarqube 6.7.6/.6.7.7 and Findbugs 3.9.2/3.9.3). Would love to see Findbugs working again in Sonarqube 6.7.x and not having to wait until Sonarqube 7.x becomes the next LTS version.

**Comment by Waize** [comment] 2019-05-06 08:43
Hi @KengoTODA,
same here as @cstsw . Would love using findbugs with Sonarqube 6.7.7 LTS.

Can you please fix this issue?

**Comment by jloisel** [comment] 2019-05-06 13:43
Works fine with Sonarqube 7.6+ now. Thanks!

**Comment by spmason** [comment] 2019-05-07 13:19
Just to add - I had this problem with Sonar 6.7.4 after upgrading to Sonar-Java 5.12 and the new version of this plugin is only compatible with Sonar 7.8 so I couldn't use it

In the end I downgraded Sonar-Java to 5.11 and everything is working properly now. You can grab the jar for 5.11 from here: https://binaries.sonarsource.com/Distribution/sonar-java-plugin/. Just manually copy it to `extensions/plugins/` and restart Sonar

**Comment by Lonzak** [comment] 2019-05-08 16:14
We basically need a Spotbugs version 3.9.4 for the current Sonar LTS version 6.7.7. (Because 3.11 won't run on 6.7.X)

**Comment by alixwar** [comment] 2019-05-09 14:39
There's still a month until SonarQube 7.x becomes the new LTS version. We will unfortunately be forced to abandon FindBugs as many of our projects cannot analyze at all because of this issue. Please prioritize LTS version compatibility

**Comment by jloisel** [comment] 2019-05-09 18:11
Works fine in Sonarqube 7.6, can't you migrate to this version instead of dropping findbugs (which is really useful)?

**Comment by cstsw** [comment] 2019-05-10 08:15
@alixwar I also preferred staying with current LTS version 6.7.7 and downgraded the Sonar-Java-Plugin as suggested by @spmason. Didn't want to skip the Findbugs analysis until the plugin is ported for Sonar 6.7.x or 7.x becomes LTS and I probably won't need the newer Java-Plugin in the meantime.

**Comment by alixwar** [comment] 2019-05-10 08:39
@jloisel I work for a big organization (with an enterprise license for SonarQube) with many projects and to avoid this kind of operational issues we have decided to go use the LTS version (we expect this version to be "stable" and that any issues are fixed promptly) so unfortunately this is not an alternative for us.

@cstsw We have an automated pipeline that always keeps our plugins up-to-date so while I agree that this would be a reasonable alternative I am very reluctant to break our automated setup

**Comment by upendran** [comment] 2019-08-22 23:00
i got over this issue by replacing findbugs with the latest version - sonar-findbugs-plugin-3.11.0.jar along with Java plugin  version - 5.13.1.18282. Running Sonarqube on K8s.
